services:
  flask-app:
    container_name: flask-app
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:////instance/app.db
      
    depends_on:
      - rabbitmq
    volumes:
      - ./instance/app.db:/instance/app.db
  
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  worker:
    build:
      context: .
    depends_on:
      - rabbitmq
      - flask-app
    environment:
      - DATABASE_URL=sqlite:////instance/app.db
      
    volumes:
      - ./instance/app.db:/instance/app.db
    command: python -u worker.py  
    
  bot:
    build:
      context: .
    depends_on:
      - rabbitmq
    environment:
      - DATABASE_URL=sqlite:////instance/app.db
      
    volumes:
      - ./instance/app.db:/instance/app.db
    command: python -u bot.py  

volumes:
  rabbitmq_data:
    driver: local

networks:
  default:
