version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"  # RabbitMQ Management Plugin (web UI)
      - "5672:5672"    # RabbitMQ AMQP protocol port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
